# Generated by Django 5.1.4 on 2024-12-06 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_evento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('relator', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evento_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
